//! SVG writer.

use super::num;
use crate::config::OutputConfig;
use crate::geom::{Seg, SubPath};
use crate::model::VectorImage;

/// Serialise one subpath as SVG path data.
pub fn subpath_data(sp: &SubPath, precision: u32) -> String {
    let p = precision;
    let mut d = String::new();
    d.push_str(&format!("M{} {}", num(sp.start.x, p), num(sp.start.y, p)));
    let mut prev_cmd = ' ';
    for seg in &sp.segs {
        match *seg {
            Seg::Line { to } => {
                // Repeated commands of the same kind may omit the letter.
                if prev_cmd == 'L' {
                    d.push(' ');
                } else {
                    d.push('L');
                    prev_cmd = 'L';
                }
                d.push_str(&format!("{} {}", num(to.x, p), num(to.y, p)));
            }
            Seg::Cubic { c1, c2, to } => {
                if prev_cmd == 'C' {
                    d.push(' ');
                } else {
                    d.push('C');
                    prev_cmd = 'C';
                }
                d.push_str(&format!(
                    "{} {} {} {} {} {}",
                    num(c1.x, p),
                    num(c1.y, p),
                    num(c2.x, p),
                    num(c2.y, p),
                    num(to.x, p),
                    num(to.y, p)
                ));
            }
            Seg::Arc { r, large, sweep, to } => {
                if prev_cmd == 'A' {
                    d.push(' ');
                } else {
                    d.push('A');
                    prev_cmd = 'A';
                }
                d.push_str(&format!(
                    "{} {} 0 {} {} {} {}",
                    num(r, p),
                    num(r, p),
                    large as u8,
                    sweep as u8,
                    num(to.x, p),
                    num(to.y, p)
                ));
            }
        }
    }
    if sp.closed {
        d.push('Z');
    }
    d
}

pub fn write(image: &VectorImage, cfg: &OutputConfig) -> String {
    let p = cfg.precision;
    let w = num(image.width, p);
    let h = num(image.height, p);
    let mut s = String::with_capacity(4096);

    s.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    s.push_str(&format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{w}\" height=\"{h}\" \
         viewBox=\"0 0 {w} {h}\" shape-rendering=\"geometricPrecision\">\n"
    ));
    s.push_str("<!-- Generated by Vectify -->\n");

    if let Some(bg) = image.background {
        s.push_str(&format!(
            "<rect width=\"{w}\" height=\"{h}\" fill=\"{}\"/>\n",
            bg.to_hex()
        ));
    }

    for shape in &image.shapes {
        if shape.subpaths.is_empty() {
            continue;
        }
        let d: Vec<String> = shape
            .subpaths
            .iter()
            .map(|sp| subpath_data(sp, p))
            .collect();
        s.push_str("<path d=\"");
        s.push_str(&d.join(""));
        s.push_str("\" fill=\"");
        s.push_str(&shape.color.to_hex());
        s.push('"');
        if shape.color.a != 255 {
            s.push_str(&format!(
                " fill-opacity=\"{}\"",
                num(shape.color.a as f64 / 255.0, 3)
            ));
        }
        s.push_str("/>\n");
    }

    s.push_str("</svg>\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::color::Rgba8;
    use crate::geom::pt;
    use crate::model::Shape;

    fn doc() -> VectorImage {
        let mut sp = SubPath::new(pt(0.0, 0.0));
        sp.segs.push(Seg::Line { to: pt(10.0, 0.0) });
        sp.segs.push(Seg::Line { to: pt(10.0, 10.0) });
        sp.segs.push(Seg::Cubic {
            c1: pt(6.0, 12.0),
            c2: pt(3.0, 12.0),
            to: pt(0.0, 10.0),
        });
        sp.segs.push(Seg::Line { to: pt(0.0, 0.0) });
        sp.closed = true;
        VectorImage {
            width: 10.0,
            height: 10.0,
            shapes: vec![Shape {
                color: Rgba8::opaque(0x33, 0x66, 0x99),
                subpaths: vec![sp],
            }],
            background: None,
        }
    }

    #[test]
    fn emits_wellformed_svg() {
        let s = write(&doc(), &OutputConfig::default());
        assert!(s.starts_with("<?xml"));
        assert!(s.contains("<svg xmlns=\"http://www.w3.org/2000/svg\""));
        assert!(s.contains("viewBox=\"0 0 10 10\""));
        assert!(s.contains("fill=\"#336699\""));
        assert!(s.trim_end().ends_with("</svg>"));
    }

    #[test]
    fn path_data_uses_expected_commands() {
        let d = subpath_data(&doc().shapes[0].subpaths[0], 3);
        assert!(d.starts_with("M0 0"));
        assert!(d.contains('L'));
        assert!(d.contains('C'));
        assert!(d.ends_with('Z'));
        // Consecutive lines share one command letter.
        assert_eq!(d.matches('L').count(), 2, "{d}");
    }

    #[test]
    fn arcs_serialise_with_both_flags() {
        let mut sp = SubPath::new(pt(0.0, 0.0));
        sp.segs.push(Seg::Arc {
            r: 5.0,
            large: true,
            sweep: false,
            to: pt(8.0, 0.0),
        });
        let d = subpath_data(&sp, 3);
        assert!(d.contains("A5 5 0 1 0 8 0"), "{d}");
    }

    #[test]
    fn translucent_fill_emits_opacity() {
        let mut v = doc();
        v.shapes[0].color = Rgba8::new(10, 20, 30, 128);
        let s = write(&v, &OutputConfig::default());
        assert!(s.contains("fill-opacity=\"0.502\""), "{s}");
    }
}
